import Foundation
import Network
import Security

/// HTTPS server on port 9877 (pf redirects 443 → 9877).
/// Requires a PKCS12 identity generated by Setup at `TLSServer.p12Path`.
final class TLSServer {

    // MARK: - Config (referenced by SetupManager too)

    static let port: NWEndpoint.Port = 9877
    static let certDir    = "/Library/GoLinks"
    static let p12Path    = "/Library/GoLinks/server.p12"
    static let p12Password = "golinks123"

    // MARK: - State

    private var listener: NWListener?
    private var running = false
    private weak var store: GoLinkStore?

    // MARK: - Lifecycle

    func start(store: GoLinkStore) {
        guard !running else { return }
        self.store = store

        guard let identity = loadIdentity() else {
            print("[GoLinks] TLS identity not found – HTTPS disabled (run Setup first)")
            return
        }

        let tlsOpts = NWProtocolTLS.Options()
        sec_protocol_options_set_local_identity(
            tlsOpts.securityProtocolOptions,
            sec_identity_create(identity)!
        )

        let params = NWParameters(tls: tlsOpts)
        params.allowLocalEndpointReuse = true

        do {
            listener = try NWListener(using: params, on: Self.port)
        } catch {
            print("[GoLinks] TLS listener init failed: \(error)")
            return
        }

        running = true
        listener?.newConnectionHandler = { [weak self] conn in
            self?.handle(connection: conn)
        }
        listener?.stateUpdateHandler = { state in
            if case .failed(let err) = state {
                print("[GoLinks] TLS server error: \(err)")
            }
        }
        listener?.start(queue: .global(qos: .userInitiated))
        print("[GoLinks] HTTPS server listening on port \(Self.port.rawValue)")
    }

    func stop() {
        running = false
        listener?.cancel()
        listener = nil
    }

    // MARK: - Identity loading

    private func loadIdentity() -> SecIdentity? {
        guard let data = try? Data(contentsOf: URL(fileURLWithPath: Self.p12Path)) else {
            return nil
        }
        let opts: [String: Any] = [kSecImportExportPassphrase as String: Self.p12Password]
        var items: CFArray?
        guard SecPKCS12Import(data as CFData, opts as CFDictionary, &items) == errSecSuccess,
              let arr = items as? [[String: Any]],
              let identityRef = arr.first?[kSecImportItemIdentity as String]
        else { return nil }
        return (identityRef as! SecIdentity)
    }

    // MARK: - Connection handling

    private func handle(connection: NWConnection) {
        connection.start(queue: .global(qos: .userInitiated))
        connection.receive(minimumIncompleteLength: 1, maximumLength: 8192) { [weak self] data, _, _, _ in
            guard let self, let data, !data.isEmpty else {
                connection.cancel()
                return
            }
            let request = String(data: data, encoding: .utf8) ?? ""
            let response = self.buildResponse(for: request)
            connection.send(content: response.data(using: .utf8),
                            completion: .contentProcessed { _ in connection.cancel() })
        }
    }

    // MARK: - Response building

    private func buildResponse(for requestText: String) -> String {
        let lines = requestText.components(separatedBy: "\r\n")
        guard let firstLine = lines.first, firstLine.hasPrefix("GET ") else {
            return httpResponse(status: "405 Method Not Allowed", body: "<h1>Method Not Allowed</h1>")
        }
        let parts = firstLine.split(separator: " ", maxSplits: 2, omittingEmptySubsequences: false)
        guard parts.count >= 2 else {
            return httpResponse(status: "400 Bad Request", body: "<h1>Bad Request</h1>")
        }

        var rawPath = String(parts[1])
        if rawPath.hasPrefix("/") { rawPath = String(rawPath.dropFirst()) }

        let queryIdx = rawPath.firstIndex(of: "?")
        let shortName: String
        let queryString: String
        if let qi = queryIdx {
            shortName = String(rawPath[rawPath.startIndex..<qi])
            queryString = String(rawPath[qi...])
        } else {
            shortName = rawPath
            queryString = ""
        }

        if shortName.isEmpty { return indexPage() }

        var destination: String?
        if let s = store { DispatchQueue.main.sync { destination = s.destination(for: shortName) } }

        if let dest = destination {
            return "HTTP/1.1 302 Found\r\nLocation: \(dest)\(queryString)\r\nCache-Control: no-cache\r\nContent-Length: 0\r\n\r\n"
        } else {
            let body = """
            <html><head><title>Go Link Not Found</title>
            <style>body{font-family:system-ui;padding:2rem;max-width:600px;margin:auto}a{color:#007aff}</style>
            </head><body>
            <h1>&#128279; go/<em>\(escapeHTML(shortName))</em> not found</h1>
            <p>Open the <strong>Go Links</strong> menu bar app to add it.</p>
            <p><a href="https://go/">&#8592; View all go links</a></p>
            </body></html>
            """
            return httpResponse(status: "404 Not Found", body: body)
        }
    }

    private func indexPage() -> String {
        var links: [GoLink] = []
        if let s = store { DispatchQueue.main.sync { links = s.links } }
        var rows = ""
        for link in links.sorted(by: { $0.shortName < $1.shortName }) {
            rows += "<tr><td><a href=\"https://go/\(link.shortName)\">go/\(escapeHTML(link.shortName))</a></td>"
            rows += "<td><a href=\"\(escapeHTML(link.destinationURL))\" target=\"_blank\">\(escapeHTML(link.destinationURL))</a></td></tr>"
        }
        let body = """
        <html><head><title>Go Links</title>
        <style>body{font-family:system-ui;padding:2rem;max-width:800px;margin:auto;background:#f5f5f5}
        h1{color:#1d1d1f}
        table{width:100%;border-collapse:collapse;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1)}
        th{background:#007aff;color:#fff;padding:10px 14px;text-align:left}
        td{padding:10px 14px;border-bottom:1px solid #eee}tr:last-child td{border-bottom:none}
        a{color:#007aff;text-decoration:none}a:hover{text-decoration:underline}
        .empty{text-align:center;padding:2rem;color:#888}</style></head><body>
        <h1>&#128279; Go Links</h1>
        \(links.isEmpty
            ? "<p class='empty'>No go links configured. Open the menu bar app to add some.</p>"
            : "<table><thead><tr><th>Go Link</th><th>Destination</th></tr></thead><tbody>\(rows)</tbody></table>"
        )
        </body></html>
        """
        return httpResponse(status: "200 OK", body: body, contentType: "text/html; charset=utf-8")
    }

    private func httpResponse(status: String, body: String,
                               contentType: String = "text/html; charset=utf-8") -> String {
        "HTTP/1.1 \(status)\r\nContent-Type: \(contentType)\r\nContent-Length: \(body.utf8.count)\r\nCache-Control: no-cache\r\n\r\n\(body)"
    }

    private func escapeHTML(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
         .replacingOccurrences(of: "<", with: "&lt;")
         .replacingOccurrences(of: ">", with: "&gt;")
         .replacingOccurrences(of: "\"", with: "&quot;")
    }
}
